### ISSUE TITLE
Express: Why 'trust proxy' 'loopback, linklocal, uniquelocal' ?

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/example-single-process#1]
Just out of curiosity and documentation purposes, why do we set these:

```JS
app.set('trust proxy', 'loopback, linklocal, uniquelocal');
```
https://github.com/oddnetworks/example-single-process/blob/master/server.js#L47

**Comment by blainsmith** [comment]
This was used in conjunction with Fastly. It sets the proper IP address on `req.ip`.

**Comment by kixxauth** [comment]
Interesting.

Cool, thanks.
